<?xml version="1.0"?>
<!DOCTYPE html>
<html>
  <head>
    <title>C++ Exceptions</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="stylesheet.en.css"/>
    <!--
    <meta name="keywords" content="KW1, KW2, KW3"/>

    <meta name="author" content="AUTHOR"/>
    <meta name="description" content="A_DESCRIPTION"/>
    <meta name="FIELD_NAME" content="FIELD_VALUE"/>
    -->
  </head>

  <body lang="en" class="computing">

    <nav>
      <div>
        <p> <a href="cpp.exception-handling-macros.html">Exception-Handling Macros</a> </p>
      </div>
      <div>
        <p> <a rel="prev" href="cpp.html">The C++ Programming Language</a> </p>
        <p> <a href="computing.html">Computing</a> </p>
      </div>
    </nav>

    <main>
      <h1>C++ Exceptions</h1>
      <p>Exceptions are exceptional conditions. Exception handling manages situations that otherwise would make the system crash or misbehave. Exceptions are classes that are <em>thown</em> or returned from code inside a <q>try</q> <a href="programming.block.html" target="_blank">block</a> to be dealt in a <q>catch</q> block.</p>
      <p>This is the basic structure of exception handling for handling a generic object of class <code class="classname">exception</code>:</p>
      <pre>#include &lt;exception&gt;

try {
  // ...
  throw exception(); // construct and exception object
  // ...
} catch (exception &amp; ex) {
  cout &lt;&lt; "exception bearing message: \"" &lt;&lt; ex.what() &lt;&lt; "\" has been thrown..." &lt;&lt; endl;
} // code resumes here</pre>

      <section>
        <h2>Class <code class="classname">std::exception</code></h2>
        <p>Class <code class="classname">exception</code> is declared in <kbd>&lt;exception&gt;</kbd>. It cannot be initialized with a string message. Thus, to handle an exception in a <code>catch</code> clause, you may use the <code class="classname">exception</code> interface. The interface of all standard exceptions classes contains only one member that can be used to get additional information besides the type itself: the member function <code class="method">what()</code>, which returns a null-terminated byte string. The content of the string is implementation defined. The C-string, returned by <code class="method">what()</code>, is valid until the exception object from which it is obtained gets destroyed.</p>
        <pre>#include &lt;exception&gt;
class exception { // since C++11
                  // all member functions are constexpr
                  // since C++26
public:
  exception&amp; operator=(const exception&amp; <var>other</var>) noexcept; // since C++11
                                                                            // constexpr since C++26
  virtual const char* what()                                const noexcept; //
                                                                            // constexpr since C++26
  exception() noexcept;
  exception(const exception&amp; <var>other</var>) noexcept;
};</pre>
        <p>(The remaining members of the standard exception classes create, copy, assign, and destroy exception objects. Note that besides <code class="method">what()</code> there is no additional member for any of the standard exception classes that describes the kind of exception. For example, there is no portable way to find out the context of an exception or the faulty index of a range error. Thus, a portable evaluation of an exception could only print the message returned from, well, <code class="method">what()</code>.)</p>
      </section>

      <section>
        <h2>Exception Action</h2>
        <p>An exception thrown transfers control to the first matching <kbd>catch</kbd> block after all objects constructed in the <kbd>try</kbd> block have been deleted.</p>
      </section>

      <section>
        <h2>The <code class="classname">exception</code> classes</h2>
        <p>These are the exception classes, derived from class <code>exception</code>:</p>
        <ul>
          <li><code class="classname">bad_alloc</code>: thrown whenever the global operator <code>new</code> fails (except when the <code>nothrow</code> version of new is used). This is probably the most important exception because it might occur at any time in any nontrivial program.</li>
          <li><code class="classname">bad_cast</code>: thrown by the <code>dynamic_cast</code> operator if a type conversion on a reference fails at runtime.</li>
          <li><code class="classname">bad_typeid</code>: thrown by the <code>typeid</code> operator for runtime type identification. If the argument to typeid is zero or the null pointer</li>
          <li>
            <p><code class="classname">logic_error</code>:</p>
            <ul>
              <li>
                <p><code class="classname">domain_error</code>: used to report a domain error. The <dfn>domain</dfn> here is the subset of values that a function is defined for, such as positive numbers for the square root functions.</p>
                <p>No component of the standard library throws exceptions of this type. It is designed as a standard exception to be thrown by programs.</p>
              </li>
              <li><code class="classname">invalid_argument</code>: used to report invalid arguments, such as when a bitset (array of bits) is initialized with a char other than &apos;0&apos; or &apos;1&apos;.</li>
              <li><code class="classname">length_error</code>: used to report an attempt to do something that exceeds a maximum allowable size, such as appending too many characters to a string.</li>
              <li>
                <p><code class="classname">out_of_range</code>: used to report that an argument value is not in the expected range, such as when a wrong index is used in an array-like collection or string.</p>
                <p>This exception is typically thrown in array-based classes by the <code>at(<var>INDEX</var>)</code> method:</p>
                <pre>std::vector&lt;int&gt; myvector(10);
  try {
    myvector.at(20)=100;      // vector::at throws an out-of-range
  }</pre>
                <p>It the <code>operator[](<var>INDEX</var>)</code> member is used instead, no exception is thrown and the process crashes or the wrong memory is accessed without a warning if the range is exceded.</p>
              </li>
            </ul>
          </li>
          <li><code class="classname">ios_base::failure</code>: may be thrown when a stream changes its state due to an error or end-of-file.</li>

          <li>
            <p>runtime_error: used to report errors that can only be detected during runtime. It serves as a base class for several runtime error exceptions:</p>
            <ul>
              <li><code class="classname">range_error</code></li>
              <li><code class="classname">overflow_error</code></li>
              <li><code class="classname">underflow_error</code></li>
            </ul>
          </li>

          <li><code class="classname">bad_exception</code>: used to handle unexpected exceptions. It does this by using the function <code class="function">unexpected()</code>. <code class="function">unexpected()</code> is called if a function throws an exception that is not listed in an exception specification</li>
        </ul>
      </section>

      <section>
        <h2>Header Files for Exception Classes</h2>
        <p>The base class exception and class <code class="classname">bad_exception</code> are defined in <code>&lt;exception&gt;</code>. Class <code class="classname">bad_alloc</code> is defined in <code>&lt;new&gt;</code>. Classes <code class="classname">bad_cast</code> and <code class="classname">bad_typeid</code> are defined in <code>&lt;typeinfo&gt;</code>. Class <code class="classname">ios_base::failure</code> is defined in <code>&lt;ios&gt;</code>. All other classes are defined in <code>&lt;stdexcept&gt;</code>.</p>
      </section>

      <section id="writing-your-own">
        <h2>Writing Your Own Exception Classes</h2>
        <p>To write an exception class, you should:</p>
        <ol>
          <li>
            <p>Derive your class from <code>std::exception</code> or some other STL exception class, as in</p>
            <pre>class <var>my_exception_class</var> : public std::exception {...</pre>
          </li>
          <li>
            <p>override the <code>virtual const char* what() const noexcept</code> method in <code>std::exception</code></p>
          </li>
          <li>
            <p>Optionally add some features such as initializing with a string or printing detailed information, as explained in the following subsections.</p>
          </li>
        </ol>
        <section>
          <h3>Writing Exception Classes that Initialize with a String</h3>
          <p>Just add a non-public const string member and a constructor that takes a string:</p>
          <pre>#include &lt;exception&gt;
class string_initializable_exception : public std::exception {
  const std::string str;
public:
  const char* what() const noexcept override {
    return str.c_str();
  };
  string_initializable_exception(const char * txt) : str(txt) {};
};</pre>
          <p><strong>Note</strong> Quite probably you don&apos;t want to provide a default constructor, though.</p>

        </section>
        <section>
          <h3>Writing Exception Classes that Build a Formated String through an <code>std::sstream</code></h3>
          <p>You want to code an exception whose error message is as rich in information as possible by incorporating input parameters into the string that member <code>what()</code> outputs.</p>
          <p>In all the examples in this subsection, <code>std::stringstream</code> <var>ss</var> is built with parameters (in the constructor&apos;s body), then assigned to member <code>std::string</code> <var>s</var>, wherefrom a C-string is extracted.</p>
          <p>Yes, you might build your exception message outside your exception object and then initialize an <code>string_initializable_exception</code> object with that string. But let us assume you aim for something more <q>automatic</q>. You want to build the error message inside your exception object.</p>
          <p>Now, since initialization is complex, member string <var>s</var> must not be marked as <code>const</code> as the message string needs to be built in stages inside the constructor&apos;s body, as already explained.</p>
          <hr/>
          <p>I shall first illustrate a simple class that takes one integer parameter, <var>x</var>:</p>
          <pre>#include &lt;exception&gt;
#include &lt;sstream&gt;

class x_exception : public std::exception {
  std::string        s;
  std::stringstream ss;
public:
  const char* what() const noexcept override {
    return s.c_str();
  };
  x_exception() = delete;
  x_exception(int x) : s("x=") {
    ss &lt;&lt; x;
    s += ss.str();
  };
};</pre>
          <p>Here, <code>std::stringstream</code> <var>ss</var> is used for converting a number to a string.</p>
          <hr/>
          <p>The next example is more sophisticated and allows for more complexity.</p>
          <p>Also, two parameters of deducible types <code>X</code> and <code>Y</code> are read:</p>
          <pre>...</pre>

          <pre>...</pre>
        </section>
      </section>

      <section>
        <h2>Order of <kbd>catch</kbd> blocks</h2>
        <p>Catch blocks for exceptions by reference will also latch onto derived exception classes, so it is advisable to place the most specific catch blocks at the start.</p>
        <p>Lastly, <q>all exceptions</q> is selected for as <kbd>catch (...)</kbd>. Here is an example. Assume that <code class="classname">derived_exception</code> is derived from <code class="classname">exception</code>, and that there are other exceptions not derived from <code class="classname">exception</code>:</p>
        <pre>#include &lt;exception&gt;

try {
  // exception-throwing code
} catch (derived_exception &amp; dex) {
  // code handling derived_exception
} catch (exception &amp; dex) {
  // code handling exception objects and derived objects
} catch (...) {
  // code handling all remaining exceptions
}
// code resumes here</pre>
      </section>

      <section>
        <h2>Exception specification</h2>
        <p>A function may be declared to throw only one or several classes of exceptions:</p>
        <pre>voide f() throw (excpt1, excpt2);</pre>
        <p>Then, if <code class="function">f()</code> throws a different exception, global <code class="function">unexpected()</code> is called.</p>
        <p>An empty specification list means that no exception may be thrown.</p>
        <p>Exception specifications help other developers understand how your code works and behaves.</p>
      </section>

    </main>

  </body>

</html>
